# Generated by Django 4.2 on 2023-09-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_joind',
            new_name='date_joined',
        ),
    ]
